In [21]:
import torch
import numpy as np

import matplotlib.pyplot as plt

import torch.optim as optim
import torch.nn as nn


In [22]:
## inputs
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]

## outputs
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]


t_c = torch.tensor(   t_c   )
t_u = torch.tensor(   t_u   )

print(t_u.shape)
print(t_c.shape)


t_c = t_c.unsqueeze(1)
t_u = t_u.unsqueeze(1)

print(t_u.shape)
print(t_c.shape)


torch.Size([11])
torch.Size([11])
torch.Size([11, 1])
torch.Size([11, 1])


## Splitting the data

In [23]:
n_samples = t_u.shape[0]
n_samples

11

In [24]:
n_val = int(  0.3 * n_samples  )
n_val

3

In [25]:
shuffled_indeces = torch.randperm(  n_samples   )
shuffled_indeces 

tensor([ 7,  2,  9, 10,  5,  8,  1,  0,  6,  3,  4])

In [26]:
train_indeces =  shuffled_indeces[:-n_val]
val_indeces   = shuffled_indeces[-n_val:]
print(train_indeces)

tensor([ 7,  2,  9, 10,  5,  8,  1,  0])


In [27]:
print(val_indeces)

tensor([6, 3, 4])


In [28]:
train_t_u = t_u[train_indeces]
train_t_c = t_c[train_indeces]

In [29]:
val_t_u = t_u[val_indeces]
val_t_c = t_c[val_indeces]

## Training loop

In [35]:

def training_loop(n_epochs, optimizer, model, loss_fn, train_t_u, val_t_u, train_t_c, val_t_c):
    
    for epoch in range(1, n_epochs):
        
        train_t_p  = model(train_t_u)
        train_loss = loss_fn(train_t_p, train_t_c)
        
        val_t_p = model(val_t_u)
        val_loss = loss_fn(val_t_p, val_t_c)
        
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()
        
        
        if epoch % 500 == 0:
            print("train loss: ", train_loss.item())
            print("val loss: ",   val_loss.item())
        
    


## Architecture

In [36]:

def model_fn_linear():
    
    return nn.Linear(1, 1)


In [37]:
## MLP

def model_fn_nn_1hidden():
    
    seq_model = nn.Sequential(
         nn.Linear(1 , 13),
         nn.Tanh(),
         nn.Linear(13  ,1)

    )
    
    return seq_model
    


In [52]:

## nn.ReLU()

def model_deep_learning_3hidden():
    
    seq_model = nn.Sequential(
        
         nn.Linear(1 , 20),
         nn.ReLU(),
         nn.Linear(20  ,10),
         nn.Tanh(),
         nn.Linear(10  ,5),
         nn.Tanh(),
         nn.Linear(5 ,  1)

    )
    
    return seq_model


## Function Calls

In [53]:

## model = model_fn_linear()
## model =  model_fn_nn_1hidden()
model =  model_deep_learning_3hidden()

optimizer = optim.Adam(model.parameters() , lr = 0.001)
loss_fn = nn.MSELoss()



In [54]:

result = training_loop(
            n_epochs = 30000,
            optimizer = optimizer,
            model = model,
            loss_fn = loss_fn,
            train_t_u = train_t_u,
            val_t_u   = val_t_u,
            train_t_c = train_t_c,
            val_t_c   = val_t_c
)

train loss:  78.58934020996094
val loss:  215.1525115966797
train loss:  48.62614440917969
val loss:  167.4312286376953
train loss:  31.004980087280273
val loss:  130.8607940673828
train loss:  18.87727928161621
val loss:  104.89404296875
train loss:  11.441737174987793
val loss:  86.60350799560547
train loss:  7.45806360244751
val loss:  74.49284362792969
train loss:  5.676608562469482
val loss:  67.0584487915039
train loss:  4.6386590003967285
val loss:  59.22708511352539
train loss:  3.5726938247680664
val loss:  50.46974563598633
train loss:  2.478032350540161
val loss:  42.479862213134766
train loss:  1.4935212135314941
val loss:  35.71139144897461
train loss:  0.788875937461853
val loss:  30.15550422668457
train loss:  0.4807080030441284
val loss:  26.210769653320312
train loss:  0.34020906686782837
val loss:  23.60636329650879
train loss:  0.292327880859375
val loss:  22.191518783569336
train loss:  0.3289414346218109
val loss:  21.451568603515625
train loss:  0.2572538554668426

In [47]:
## celsius from fehrenheit
## 100 c = 212 f 


my_temp = model(val_t_u)

my_temp

tensor([[ 0.6733],
        [26.5154],
        [12.7329]], grad_fn=<AddmmBackward0>)

In [48]:
print(val_t_c)

tensor([[ 3.],
        [28.],
        [11.]])


In [51]:
my_temp = model(val_t_u)

my_temp

tensor([[ 0.4482],
        [34.1496],
        [14.5295]], grad_fn=<AddmmBackward0>)

In [55]:
my_temp = model(val_t_u)

my_temp

tensor([[ 0.4378],
        [21.5400],
        [14.5392]], grad_fn=<AddmmBackward0>)